version: '3.8'

services:
  control-tower:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/app/build/db
    depends_on:
      - control-tower-database

  control-tower-database:
    image: oscarfonts/h2
    ports:
      - "9091:9091"
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data: