version: '3.8'

services:
  control-tower:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/app/build/db
    depends_on:
      - control-tower-database
    networks:
      - some-net
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB

  control-tower-database:
    image: oscarfonts/h2
    ports:
      - "9091:9091"
    volumes:
      - h2-data:/opt/h2-data
    networks:
      - some-net

  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
    networks:
      - some-net

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    networks:
      - some-net

networks:
  some-net:
    driver: bridge

volumes:
  h2-data: